# Generated by Django 2.2.4 on 2019-08-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CredentialOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challenge", models.TextField()),
                ("username", models.TextField()),
                ("display_name", models.TextField()),
                ("ukey", models.TextField()),
            ],
        )
    ]
