# Generated by Django 2.2.4 on 2019-08-28 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webauthn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialoptions",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credential_options",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
