# Generated by Django 2.2.4 on 2019-08-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("webauthn", "0002_credentialoptions_user")]

    operations = [
        migrations.AddField(
            model_name="credentialoptions",
            name="credential_id",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="credentialoptions",
            name="sign_count",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
