# Generated by Django 2.2.4 on 2019-08-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("webauthn", "0003_auto_20190828_0739")]

    operations = [
        migrations.AlterField(
            model_name="credentialoptions",
            name="sign_count",
            field=models.IntegerField(null=True),
        )
    ]
