# Generated by Django 2.2.4 on 2019-08-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("webauthn", "0004_auto_20190828_0740")]

    operations = [
        migrations.AddField(
            model_name="credentialoptions",
            name="public_key",
            field=models.TextField(default=""),
            preserve_default=False,
        )
    ]
